import { Check, Download, FileImage, Pause, Play, Redo2, ScanSearch, Trash2, Undo2 } from "lucide-react";
import type { AnchorCorrespondence, ExtractionIntent, FeatureDraft, MultiPointTrack, PointSeed, PointTrack, TrackingEvent, Roi } from "@subpixel/contracts";
import { RoiCanvas, type CanvasMode } from "../roi/RoiCanvas";
import { EventTimeline } from "./EventTimeline";
import { MetricStrip } from "./MetricStrip";
import { TrackTable } from "./TrackTable";
import type { ExportFormat } from "../report/exportClient";
import { RecoveryAnchorsPanel } from "./RecoveryAnchorsPanel";

type Props = {
  image?: CanvasImageSource; sourceSize?: { width: number; height: number }; draft?: FeatureDraft; intent: ExtractionIntent;
  onIntentChange: (intent: ExtractionIntent) => void; onSelectionChange: (roi: Roi) => void; onConfirmDraft: () => void;
  onDeleteDraft: () => void; onDeleteSeed: (pointId: string) => void; onReinitialize: (pointId: string) => void; onUndoDelete: () => void;
  canUndoDelete: boolean; mode: CanvasMode; onModeChange: (mode: CanvasMode) => void; seeds: PointSeed[]; multiTracks: MultiPointTrack[];
  tracks: PointTrack[]; events: TrackingEvent[]; running: boolean; onToggle: () => void; onFiles: (files: File[]) => void;
  onExport: (format: ExportFormat) => void; onReview: (frame: number) => void; recoveryPaused?: boolean; referenceImage?: CanvasImageSource; currentImage?: CanvasImageSource; onApplyRecovery?: (anchors: AnchorCorrespondence[]) => void; onRollbackRecovery?: () => void;
};

const intents: [ExtractionIntent, string][] = [
  ["circle-center", "圆 / 椭圆中心"], ["crosshair-center", "十字丝中心"], ["diagonal-center", "对角标志中心"],
  ["corner", "单角点"], ["blob-center", "光斑中心"], ["speckle-center", "散斑中心"], ["natural-keypoint", "自然角点"],
];

export function TrackingWorkbench(props: Props) {
  const hasImage = Boolean(props.image);
  const latestByPoint = new Map(props.multiTracks.map(track => [track.pointId, track]));
  const currentTracks = props.seeds.map(seed => latestByPoint.get(seed.pointId) ?? ({ pointId: seed.pointId, model: seed.model, predicted: seed.snapped, refined: seed.snapped, confidence: seed.candidateScore, state: "valid" as const, frame: 0, timestampMs: 0, residual: 0, flowErrorForwardBackward: null, ncc: null, descriptorDistance: null, epipolarError: null, relocationMethod: "none" as const }));
  return <main className="app-shell">
    <header className="topbar"><div><span className="brand-mark"><ScanSearch size={18} /></span><strong>Subpixel Studio</strong><span className="version">原图 ROI 亚像素工作台</span></div><div className="header-status"><i />本地处理就绪</div></header>
    <div className="workspace">
      <aside className="left-panel">
        <section><div className="panel-title"><h3>导入</h3></div><label className="source-button"><FileImage size={17} />选择原图<input type="file" accept="image/*,video/*" multiple hidden onChange={event => props.onFiles(Array.from(event.target.files ?? []))} /></label>{props.sourceSize && <p className="native-note">原图 {props.sourceSize.width} × {props.sourceSize.height} px<br />算法与导出均使用原图像素</p>}</section>
        <section><div className="panel-title"><h3>提取类型</h3></div><select aria-label="提取类型" value={props.intent} onChange={event => props.onIntentChange(event.target.value as ExtractionIntent)} disabled={Boolean(props.draft)}>{intents.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><p className="empty-note">先选类型，再在原图上框选一个 ROI。草稿必须确认后才进入点集。</p></section>
        <section><div className="panel-title"><h3>草稿检查</h3>{props.draft && <span className={`draft-state draft-${props.draft.status}`}>{props.draft.status}</span>}</div>{props.draft ? <><dl className="roi-values"><div><dt>X</dt><dd>{props.draft.roi.x}</dd></div><div><dt>Y</dt><dd>{props.draft.roi.y}</dd></div><div><dt>W</dt><dd>{props.draft.roi.width}</dd></div><div><dt>H</dt><dd>{props.draft.roi.height}</dd></div></dl>{props.draft.refinement?.point && <p className="refined-center">中心十字丝：{props.draft.refinement.point.x.toFixed(3)}, {props.draft.refinement.point.y.toFixed(3)}<br />置信度 {Math.round(props.draft.refinement.confidence * 100)}% · 残差 {props.draft.refinement.residualPx?.toFixed(3) ?? "—"} px</p>}{props.draft.refinement?.reason && <p className="error-note">{props.draft.refinement.reason}</p>}<div className="draft-actions"><button className="primary-action" disabled={props.draft.status !== "ready" || !props.draft.refinement?.accepted} onClick={props.onConfirmDraft}><Check size={16} />确认点</button><button className="source-button danger" onClick={props.onDeleteDraft}><Trash2 size={16} />删除草稿</button></div></> : <p className="empty-note">尚未框选 ROI</p>}</section>
        <section><div className="panel-title"><h3>点列表</h3><span>{props.seeds.length}</span></div><div className="seed-list">{props.seeds.length ? props.seeds.map(seed => <div className="seed-row" key={seed.pointId}><span className="seed-dot" /><div><strong>{seed.pointId}</strong><small>{seed.intent ?? seed.model} · {seed.snapped.x.toFixed(2)}, {seed.snapped.y.toFixed(2)}</small></div><button title="重新初始化" aria-label={`重新初始化 ${seed.pointId}`} onClick={() => props.onReinitialize(seed.pointId)}><Redo2 size={14} /></button><button title="删除点" aria-label={`删除 ${seed.pointId}`} onClick={() => props.onDeleteSeed(seed.pointId)}><Trash2 size={14} /></button></div>) : <p className="empty-note">确认后的点会显示在这里</p>}</div>{props.canUndoDelete && <button className="text-button undo-delete" onClick={props.onUndoDelete}><Undo2 size={14} />撤销删除（5 秒）</button>}</section>
      </aside>
      <section className="center-stage"><MetricStrip tracks={props.tracks} latency={props.tracks.at(-1)?.durationMs ?? 0} />{props.events.at(-1) && <div className="mobile-event" role="status">{props.events.at(-1)?.message}</div>}<div className="canvas-shell">{hasImage ? <RoiCanvas image={props.image} draft={props.draft} seeds={props.seeds} tracks={currentTracks} mode={props.mode} canSelect={!props.draft && props.mode === "annotate"} onSelectionChange={props.onSelectionChange} /> : <div className="canvas-empty"><ScanSearch size={40} /><strong>请先选择原图</strong></div>}<div className="canvas-toolbar"><button className={`primary-action ${props.running ? "stop" : ""}`} disabled={!hasImage || !props.seeds.length || Boolean(props.draft)} onClick={props.onToggle}>{props.running ? <Pause size={17} /> : <Play size={17} />}{props.running ? "暂停跟踪" : "开始跟踪"}</button><label className="export-control"><Download size={16} /><select aria-label="导出格式" defaultValue="" onChange={event => { if (event.target.value) props.onExport(event.target.value as ExportFormat); event.target.value = ""; }}><option value="">导出</option><option value="pdf">PDF 报告</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="json">JSON</option><option value="images">标注图片</option><option value="video">标注视频</option></select></label></div></div>{currentTracks.length > 0 && <div className="table-wrap"><table><thead><tr><th>编号</th><th>模型</th><th>预测 X/Y</th><th>精修 X/Y</th><th>置信度</th><th>状态</th></tr></thead><tbody>{currentTracks.slice(-100).map((track, index) => <tr key={`${track.pointId}-${track.frame ?? index}`}><td>{track.pointId}</td><td>{track.model}</td><td>{track.predicted.x.toFixed(3)} / {track.predicted.y.toFixed(3)}</td><td>{track.refined.x.toFixed(3)} / {track.refined.y.toFixed(3)}</td><td>{Math.round(track.confidence * 100)}%</td><td><span className={`state state-${track.state}`}>{track.state}</span></td></tr>)}</tbody></table></div>}<TrackTable tracks={props.tracks} onReview={props.onReview} /></section>
      <aside className="right-panel"><EventTimeline events={props.events} /><section><div className="panel-title"><h3>模式</h3></div><div className="mode-switch" role="tablist">{([['annotate', '标点'], ['track', '跟踪'], ...(props.recoveryPaused ? [['recover', '恢复'] as [CanvasMode, string]] : [])] as [CanvasMode, string][]).map(([value, label]) => <button key={value} role="tab" aria-selected={props.mode === value} className={props.mode === value ? "mode-active" : ""} onClick={() => props.onModeChange(value)}>{label}</button>)}</div></section>{props.mode === "recover" && props.recoveryPaused && <RecoveryAnchorsPanel referenceImage={props.referenceImage} currentImage={props.currentImage ?? props.image} sourceSize={props.sourceSize} seeds={props.seeds} onApply={anchors => props.onApplyRecovery?.(anchors)} onRollback={() => props.onRollbackRecovery?.()} />}</aside>
    </div>
  </main>;
}
