import { Maximize2, Minus, Move, Plus } from "lucide-react";
import { useEffect, useRef, useState, type PointerEvent, type WheelEvent } from "react";
import type { FeatureDraft, MultiPointTrack, PointSeed, RefinementGeometry, Roi } from "@subpixel/contracts";

export type CanvasMode = "annotate" | "track" | "recover";
export function fitImageSize(width: number, height: number, maxDimension = 2560) { void maxDimension; return { width: Math.max(1, Math.round(width)), height: Math.max(1, Math.round(height)), scale: 1 }; }
export function computeFitScale(viewportWidth: number, viewportHeight: number, imageWidth: number, imageHeight: number) {
  if (imageWidth <= 0 || imageHeight <= 0) return 1;
  return Math.min(1, Math.max(1, viewportWidth - 28) / imageWidth, Math.max(1, viewportHeight - 28) / imageHeight);
}
export function clampViewZoom(value: number) { return Math.max(.25, Math.min(128, Number.isFinite(value) ? value : 1)); }
export function clampRoi(roi: Roi, bounds: { width: number; height: number }): Roi { const x = Math.max(0, Math.min(roi.x, Math.max(0, bounds.width - 1))); const y = Math.max(0, Math.min(roi.y, Math.max(0, bounds.height - 1))); return { x, y, width: Math.max(1, Math.min(roi.width, bounds.width - x)), height: Math.max(1, Math.min(roi.height, bounds.height - y)) }; }
export function normalizeNativeRoi(roi: Roi, bounds: { width: number; height: number }): Roi { const x = Math.max(0, Math.min(Math.floor(roi.x), Math.max(0, bounds.width - 1))); const y = Math.max(0, Math.min(Math.floor(roi.y), Math.max(0, bounds.height - 1))); const right = Math.max(x + 1, Math.min(bounds.width, Math.ceil(roi.x + roi.width))); const bottom = Math.max(y + 1, Math.min(bounds.height, Math.ceil(roi.y + roi.height))); return { x, y, width: right - x, height: bottom - y }; }
export function roiFromDrag(start: { x: number; y: number }, end: { x: number; y: number }, bounds: { width: number; height: number }): Roi { const left = Math.max(0, Math.min(start.x, end.x)); const top = Math.max(0, Math.min(start.y, end.y)); const right = Math.min(bounds.width, Math.max(start.x, end.x)); const bottom = Math.min(bounds.height, Math.max(start.y, end.y)); return { x: left, y: top, width: Math.max(1, right - left), height: Math.max(1, bottom - top) }; }
function sourceSize(image?: CanvasImageSource) { if (!image) return { width: 960, height: 600 }; const source = image as { width?: number; height?: number; videoWidth?: number; videoHeight?: number; displayWidth?: number; displayHeight?: number }; return { width: source.width ?? source.videoWidth ?? source.displayWidth ?? 960, height: source.height ?? source.videoHeight ?? source.displayHeight ?? 600 }; }
const pointString = (point: { x: number; y: number }) => `${point.x},${point.y}`;

function SvgCrosshair({ point, color, id, scale }: { point: { x: number; y: number }; color: string; id?: string; scale: number }) { const arm = 12 / Math.max(scale, 0.001); return <g data-point-id={id} className="overlay-crosshair" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"><line x1={point.x - arm} y1={point.y} x2={point.x + arm} y2={point.y} /><line x1={point.x} y1={point.y - arm} x2={point.x} y2={point.y + arm} /></g>; }
function SvgGeometry({ geometry, color, scale }: { geometry: RefinementGeometry; color: string; scale: number }) { if (geometry.kind === "ellipse" && geometry.center) return <><ellipse className="overlay-geometry" cx={geometry.center.x} cy={geometry.center.y} rx={geometry.majorAxis / 2} ry={geometry.minorAxis / 2} transform={`rotate(${geometry.angleDeg} ${pointString(geometry.center)})`} stroke={color} fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke" /><SvgCrosshair point={geometry.center} color={color} scale={scale} /></>; if (geometry.kind === "lines" && geometry.line1 && geometry.line2) return <g className="overlay-geometry" stroke={color} fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke"><line x1={geometry.line1.start.x} y1={geometry.line1.start.y} x2={geometry.line1.end.x} y2={geometry.line1.end.y} /><line x1={geometry.line2.start.x} y1={geometry.line2.start.y} x2={geometry.line2.end.x} y2={geometry.line2.end.y} /></g>; if (geometry.kind === "corner" && geometry.point) return <SvgCrosshair point={geometry.point} color={color} scale={scale} />; return null; }
type DragState = { kind: "new" | "move" | "resize"; handle?: number; start: { x: number; y: number }; initial: Roi };

export function RoiCanvas({ image, draft, roi, seeds = [], tracks = [], mode = "annotate", onSelectionChange, canSelect = true }: { image?: CanvasImageSource; draft?: FeatureDraft; roi?: Roi; seeds?: PointSeed[]; tracks?: MultiPointTrack[]; mode?: CanvasMode; onSelectionChange?: (roi: Roi) => void; canSelect?: boolean; }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const viewportRef = useRef<HTMLDivElement>(null); const [zoom, setZoom] = useState(1); const [fitScale, setFitScale] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [panMode, setPanMode] = useState(false); const [panStart, setPanStart] = useState<{ clientX: number; clientY: number; x: number; y: number }>(); const [drag, setDrag] = useState<DragState>(); const [transientRoi, setTransientRoi] = useState<Roi>();
  const dimensions = sourceSize(image); const selection = draft?.roi ?? roi ?? transientRoi; const displayScale = fitScale * zoom;
  // A camera produces a new ImageBitmap every frame. View state must reset only when the native image geometry changes, otherwise an active touch drag is cancelled by the next frame.
  useEffect(() => { setZoom(1); setPan({ x: 0, y: 0 }); setDrag(undefined); setTransientRoi(undefined); }, [dimensions.width, dimensions.height, Boolean(image)]);
  useEffect(() => { const viewport = viewportRef.current; if (!viewport || !image) return; const update = () => setFitScale(computeFitScale(viewport.clientWidth, viewport.clientHeight, dimensions.width, dimensions.height)); update(); const observer = new ResizeObserver(update); observer.observe(viewport); return () => observer.disconnect(); }, [dimensions.width, dimensions.height, Boolean(image)]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !image) return; const context = canvas.getContext("2d"); if (!context) return; context.clearRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); }, [image, dimensions.width, dimensions.height]);
  useEffect(() => { const layer = canvasRef.current?.parentElement; if (!layer) return; layer.style.left = "50%"; layer.style.top = "50%"; layer.style.transform = `translate(calc(-50% + ${pan.x}px), calc(-50% + ${pan.y}px)) scale(${displayScale})`; }, [pan.x, pan.y, displayScale]);
  const imagePoint = (event: PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) * event.currentTarget.width / rect.width, y: (event.clientY - rect.top) * event.currentTarget.height / rect.height }; };
  const handlePoints = (current: Roi) => [[current.x, current.y], [current.x + current.width / 2, current.y], [current.x + current.width, current.y], [current.x + current.width, current.y + current.height / 2], [current.x + current.width, current.y + current.height], [current.x + current.width / 2, current.y + current.height], [current.x, current.y + current.height], [current.x, current.y + current.height / 2]];
  const hitHandle = (point: { x: number; y: number }, current?: Roi) => current ? handlePoints(current).findIndex(([x, y]) => Math.hypot(point.x - x, point.y - y) <= Math.max(8 / Math.max(displayScale, 0.001), Math.min(dimensions.width, dimensions.height) / 90)) : -1;
  const updateDrag = (point: { x: number; y: number }) => { if (!drag) return; if (drag.kind === "new") { setTransientRoi(roiFromDrag(drag.start, point, dimensions)); return; } const dx = point.x - drag.start.x; const dy = point.y - drag.start.y; const initial = drag.initial; if (drag.kind === "move") { onSelectionChange?.(clampRoi({ ...initial, x: initial.x + dx, y: initial.y + dy }, dimensions)); return; } const left = drag.handle === 0 || drag.handle === 6 || drag.handle === 7; const right = drag.handle === 2 || drag.handle === 3 || drag.handle === 4; const top = drag.handle !== undefined && drag.handle <= 2; const bottom = drag.handle === 4 || drag.handle === 5 || drag.handle === 6; const x1 = left ? initial.x + dx : initial.x; const x2 = right ? initial.x + initial.width + dx : initial.x + initial.width; const y1 = top ? initial.y + dy : initial.y; const y2 = bottom ? initial.y + initial.height + dy : initial.y + initial.height; onSelectionChange?.(clampRoi({ x: Math.min(x1, x2), y: Math.min(y1, y2), width: Math.abs(x2 - x1), height: Math.abs(y2 - y1) }, dimensions)); };
  const onPointerDown = (event: PointerEvent<HTMLCanvasElement>) => { if (panMode || event.altKey || event.button === 1) { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); setPanStart({ clientX: event.clientX, clientY: event.clientY, x: pan.x, y: pan.y }); return; } if (mode !== "annotate" && mode !== "recover") return; const point = imagePoint(event); const handle = hitHandle(point, draft?.roi); if (draft?.roi && handle >= 0) setDrag({ kind: "resize", handle, start: point, initial: draft.roi }); else if (draft?.roi && point.x >= draft.roi.x && point.x <= draft.roi.x + draft.roi.width && point.y >= draft.roi.y && point.y <= draft.roi.y + draft.roi.height) setDrag({ kind: "move", start: point, initial: draft.roi }); else if (!draft && canSelect) { setDrag({ kind: "new", start: point, initial: { x: point.x, y: point.y, width: 1, height: 1 } }); setTransientRoi({ x: point.x, y: point.y, width: 1, height: 1 }); } event.currentTarget.setPointerCapture(event.pointerId); };
  const onPointerMove = (event: PointerEvent<HTMLCanvasElement>) => { if (panStart) setPan({ x: panStart.x + event.clientX - panStart.clientX, y: panStart.y + event.clientY - panStart.clientY }); else updateDrag(imagePoint(event)); };
  const onPointerUp = (event: PointerEvent<HTMLCanvasElement>) => { if (panStart) { setPanStart(undefined); return; } if (!drag) return; const point = imagePoint(event); if (drag.kind === "new") { const next = roiFromDrag(drag.start, point, dimensions); setTransientRoi(undefined); if (next.width >= 9 && next.height >= 9) onSelectionChange?.(next); } else updateDrag(point); setDrag(undefined); };
  const changeZoom = (next: number) => setZoom(clampViewZoom(next)); const onWheel = (event: WheelEvent<HTMLCanvasElement>) => { event.preventDefault(); changeZoom(zoom * (event.deltaY < 0 ? 1.15 : 1 / 1.15)); }; const handleColor = draft?.status === "invalid" ? "#f06a5f" : "#f5b700";
  return <div ref={viewportRef} className="image-viewport"><div className="image-layer" style={{ width: dimensions.width, height: dimensions.height, transform: `translate(${pan.x}px, ${pan.y}px) scale(${displayScale})` }}><canvas ref={canvasRef} width={dimensions.width} height={dimensions.height} className={`roi-canvas ${panMode ? "is-panning" : ""}`} tabIndex={0} aria-label="原图 ROI 画布" onWheel={onWheel} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={() => { setDrag(undefined); setPanStart(undefined); }} /><svg className="roi-overlay" width={dimensions.width} height={dimensions.height} viewBox={`0 0 ${dimensions.width} ${dimensions.height}`} aria-hidden="true">
    {selection && <><rect className="overlay-roi" x={selection.x} y={selection.y} width={selection.width} height={selection.height} stroke={handleColor} fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke" strokeDasharray={draft ? undefined : "10 6"} />{draft && handlePoints(selection).map(([x, y], index) => { const size = 10 / Math.max(displayScale, 0.001); return <rect key={index} className="overlay-handle" x={x - size / 2} y={y - size / 2} width={size} height={size} fill="#fff" stroke={handleColor} strokeWidth="2" vectorEffect="non-scaling-stroke" />; })}{draft?.refinement?.geometry && <SvgGeometry geometry={draft.refinement.geometry} scale={displayScale} color={draft.refinement.accepted ? "#00d4bd" : "#f06a5f"} />}</>}
    {seeds.map((seed, index) => { const color = seed.model === "natural-keypoint" ? "#4aa3ff" : "#00d4bd"; return <g key={seed.pointId} data-point-id={seed.pointId}><circle className="overlay-point" cx={seed.snapped.x} cy={seed.snapped.y} r={8 / Math.max(displayScale, 0.001)} stroke={color} fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke" /><SvgCrosshair point={seed.snapped} color={color} id={seed.pointId} scale={displayScale} />{seed.geometry && <SvgGeometry geometry={seed.geometry} scale={displayScale} color={color} />}<text x={seed.snapped.x + 12 / Math.max(displayScale, 0.001)} y={seed.snapped.y - 10 / Math.max(displayScale, 0.001)} fill={color} fontSize={14 / Math.max(displayScale, 0.001)} className="overlay-label">{index + 1}</text></g>; })}
    {tracks.map(track => { const color = track.state === "valid" ? "#37c884" : track.state === "suspect" ? "#f5b700" : "#f06a5f"; return <g key={`${track.pointId}-${track.frame}`} data-point-id={track.pointId}><line x1={track.predicted.x} y1={track.predicted.y} x2={track.refined.x} y2={track.refined.y} stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" /><SvgCrosshair point={track.refined} color={color} id={track.pointId} scale={displayScale} /></g>; })}
  </svg></div><div className="viewport-tools" aria-label="图像视图工具"><button className={panMode ? "active" : ""} title="平移图像" aria-label="平移图像" onClick={() => setPanMode(value => !value)}><Move size={16} /></button><button title="缩小图像" aria-label="缩小图像" onClick={() => changeZoom(zoom / 1.25)}><Minus size={16} /></button><span>{Math.round(zoom * 100)}%</span><button title="放大图像" aria-label="放大图像" onClick={() => changeZoom(zoom * 1.25)}><Plus size={16} /></button><button title="图像适合窗口" aria-label="图像适合窗口" onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}><Maximize2 size={16} /></button></div></div>;
}
